{
 "title": "Application Observability",
 "tags": [ "observability" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_requests_total", "legendFormat": "Total Requests" }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_errors_total", "legendFormat": "Total Errors" }
   ]
  },
  {
   "title": "Error Rate (per min)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(app_errors_total[1m]) * 60",
     "legendFormat": "errors/min"
    }
   ]
  },
  {
   "title": "Request Rate (per sec)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(app_requests_total[1m])", "legendFormat": "req/s" }
   ]
  },
  {
   "title": "Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(app_requests_total[1m])", "legendFormat": "Request Rate (req/s)" }
   ]
  },
  {
   "title": "Error Rate Over Time  (ALERT threshold: 5/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "rate(app_errors_total[1m]) * 60",
     "legendFormat": "Error Rate (errors/min)"
    }
   ]
  }
 ]
}